login:
    path: /login
    defaults: { _controller: BlogBundle:User:login, route: menu, permanent: true}

login_check:
    path: /login_check

logout:
    path: /logout
    

    

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
    
    


